version: '3.8'

services:
  scheduler:
    build: .
    container_name: saldoExtratosBancarios
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./secrets:/app/secrets
      - ./.env:/app/.env
